# --- Day 9: Rope Bridge ---
# This rope bridge creaks as you walk along it. You aren't sure how old it is, or whether it can even support your weight.

# It seems to support the Elves just fine, though. The bridge spans a gorge which was carved out by the massive river far below you.

# You step carefully; as you do, the ropes stretch and twist. You decide to distract yourself by modeling rope physics; maybe you can even figure out where not to step.

# Consider a rope with a knot at each end; these knots mark the head and the tail of the rope. If the head moves far enough away from the tail, the tail is pulled toward the head.

# Due to nebulous reasoning involving Planck lengths, you should be able to model the positions of the knots on a two-dimensional grid.
# Then, by following a hypothetical series of motions (your puzzle input) for the head, you can determine how the tail will move.

# Due to the aforementioned Planck lengths, the rope must be quite short; in fact, the head (H) and tail (T) must always be touching (diagonally adjacent and even overlapping both count as touching):

# ....
# .TH.
# ....

# ....
# .H..
# ..T.
# ....

# ...
# .H. (H covers T)
# ...
# If the head is ever two steps directly up, down, left, or right from the tail, the tail must also move one step in that direction so it remains close enough:

# .....    .....    .....
# .TH.. -> .T.H. -> ..TH.
# .....    .....    .....

# ...    ...    ...
# .T.    .T.    ...
# .H. -> ... -> .T.
# ...    .H.    .H.
# ...    ...    ...
# Otherwise, if the head and tail aren't touching and aren't in the same row or column, the tail always moves one step diagonally to keep up:

# .....    .....    .....
# .....    ..H..    ..H..
# ..H.. -> ..... -> ..T..
# .T...    .T...    .....
# .....    .....    .....

# .....    .....    .....
# .....    .....    .....
# ..H.. -> ...H. -> ..TH.
# .T...    .T...    .....
# .....    .....    .....
# You just need to work out where the tail goes as the head follows a series of motions. Assume the head and the tail both start at the same position, overlapping.

# For example:

# R 4
# U 4
# L 3
# D 1
# R 4
# D 1
# L 5
# R 2
# This series of motions moves the head right four steps, then up four steps, then left three steps, then down one step, and so on. After each step, you'll need to
# update the position of the tail if the step means the head is no longer adjacent to the tail. Visually, these motions occur as follows (s marks the starting position as a reference point):

# == Initial State ==

# ......
# ......
# ......
# ......
# H.....  (H covers T, s)

# == R 4 ==

# ......
# ......
# ......
# ......
# TH....  (T covers s)

# ......
# ......
# ......
# ......
# sTH...

# ......
# ......
# ......
# ......
# s.TH..

# ......
# ......
# ......
# ......
# s..TH.

# == U 4 ==

# ......
# ......
# ......
# ....H.
# s..T..

# ......
# ......
# ....H.
# ....T.
# s.....

# ......
# ....H.
# ....T.
# ......
# s.....

# ....H.
# ....T.
# ......
# ......
# s.....

# == L 3 ==

# ...H..
# ....T.
# ......
# ......
# s.....

# ..HT..
# ......
# ......
# ......
# s.....

# .HT...
# ......
# ......
# ......
# s.....

# == D 1 ==

# ..T...
# .H....
# ......
# ......
# s.....

# == R 4 ==

# ..T...
# ..H...
# ......
# ......
# s.....

# ..T...
# ...H..
# ......
# ......
# s.....

# ......
# ...TH.
# ......
# ......
# s.....

# ......
# ....TH
# ......
# ......
# s.....

# == D 1 ==

# ......
# ....T.
# .....H
# ......
# s.....

# == L 5 ==

# ......
# ....T.
# ....H.
# ......
# s.....--- Day 9: Rope Bridge ---
# This rope bridge creaks as you walk along it. You aren't sure how old it is, or whether it can even support your weight.

# It seems to support the Elves just fine, though. The bridge spans a gorge which was carved out by the massive river far below you.

# You step carefully; as you do, the ropes stretch and twist. You decide to distract yourself by modeling rope physics; maybe you can even figure out where not to step.

# Consider a rope with a knot at each end; these knots mark the head and the tail of the rope. If the head moves far enough away from the tail, the tail is pulled toward the head.

# Due to nebulous reasoning involving Planck lengths, you should be able to model the positions of the knots on a two-dimensional grid.
# Then, by following a hypothetical series of motions (your puzzle input) for the head, you can determine how the tail will move.

# Due to the aforementioned Planck lengths, the rope must be quite short; in fact, the head (H) and tail (T) must always be touching (diagonally adjacent and even overlapping both count as touching):

# ....
# .TH.
# ....

# ....
# .H..
# ..T.
# ....

# ...
# .H. (H covers T)
# ...
# If the head is ever two steps directly up, down, left, or right from the tail, the tail must also move one step in that direction so it remains close enough:

# .....    .....    .....
# .TH.. -> .T.H. -> ..TH.
# .....    .....    .....

# ...    ...    ...
# .T.    .T.    ...
# .H. -> ... -> .T.
# ...    .H.    .H.
# ...    ...    ...
# Otherwise, if the head and tail aren't touching and aren't in the same row or column, the tail always moves one step diagonally to keep up:

# .....    .....    .....
# .....    ..H..    ..H..
# ..H.. -> ..... -> ..T..
# .T...    .T...    .....
# .....    .....    .....

# .....    .....    .....
# .....    .....    .....
# ..H.. -> ...H. -> ..TH.
# .T...    .T...    .....
# .....    .....    .....
# You just need to work out where the tail goes as the head follows a series of motions. Assume the head and the tail both start at the same position, overlapping.

# For example:

# R 4
# U 4
# L 3
# D 1
# R 4
# D 1
# L 5
# R 2
# This series of motions moves the head right four steps, then up four steps, then left three steps, then down one step, and so on.
# After each step, you'll need to update the position of the tail if the step means the head is no longer adjacent to the tail.
# Visually, these motions occur as follows (s marks the starting position as a reference point):

# == Initial State ==

# ......
# ......
# ......
# ......
# H.....  (H covers T, s)

# == R 4 ==

# ......
# ......
# ......
# ......
# TH....  (T covers s)

# ......
# ......
# ......
# ......
# sTH...

# ......
# ......
# ......
# ......
# s.TH..

# ......
# ......
# ......
# ......
# s..TH.

# == U 4 ==

# ......
# ......
# ......
# ....H.
# s..T..

# ......
# ......
# ....H.
# ....T.
# s.....

# ......
# ....H.
# ....T.
# ......
# s.....

# ....H.
# ....T.
# ......
# ......
# s.....

# == L 3 ==

# ...H..
# ....T.
# ......
# ......
# s.....

# ..HT..
# ......
# ......
# ......
# s.....

# .HT...
# ......
# ......
# ......
# s.....

# == D 1 ==

# ..T...
# .H....
# ......
# ......
# s.....

# == R 4 ==

# ..T...
# ..H...
# ......
# ......
# s.....

# ..T...
# ...H..
# ......
# ......
# s.....

# ......
# ...TH.
# ......
# ......
# s.....

# ......
# ....TH
# ......
# ......
# s.....

# == D 1 ==

# ......
# ....T.
# .....H
# ......
# s.....

# == L 5 ==

# ......
# ....T.
# ....H.
# ......
# s.....

# ......
# ....T.
# ...H..
# ......
# s.....

# ......
# ......
# ..HT..
# ......
# s.....

# ......
# ......
# .HT...
# ......
# s.....

# ......
# ......
# HT....
# ......
# s.....

# == R 2 ==

# ......
# ......
# .H....  (H covers T)
# ......
# s.....

# ......
# ......
# .TH...
# ......
# s.....
# After simulating the rope, you can count up all of the positions the tail visited at least once.
# In this diagram, s again marks the starting position (which the tail also visited) and # marks other positions the tail visited:

# ..##..
# ...##.
# .####.
# ....#.
# s###..
# So, there are 13 positions the tail visited at least once.

# Simulate your complete hypothetical series of motions. How many positions does the tail of the rope visit at least once?

# ......
# ....T.
# ...H..
# ......
# s.....

# ......
# ......
# ..HT..
# ......
# s.....

# ......
# ......
# .HT...
# ......
# s.....

# ......
# ......
# HT....
# ......
# s.....

# == R 2 ==

# ......
# ......
# .H....  (H covers T)
# ......
# s.....

# ......
# ......
# .TH...
# ......
# s.....
# After simulating the rope, you can count up all of the positions the tail visited at least once. In this diagram, s again marks the starting position (which the tail also visited) and # marks other positions the tail visited:

# ..##..
# ...##.
# .####.
# ....#.
# s###..
# So, there are 13 positions the tail visited at least once.

# Simulate your complete hypothetical series of motions. How many positions does the tail of the rope visit at least once?


class Rope:
    def __init__(self) -> None:
        # set a good starting state
        self.head_x = 0
        self.head_y = 0
        self.tail_x = 0
        self.tail_y = 0
        self.tail_visited = set([(self.tail_x, self.tail_y)])
        print(f"self.tail_visited is {self.tail_visited}")

    def move_left(self):
        print("moving left")
        self.head_x -= 1
        self.tail_follow()

    def move_right(self):
        print("moving right")
        self.head_x += 1
        self.tail_follow()

    def move_up(self):
        print("moving up")
        self.head_y -= 1
        self.tail_follow()

    def move_down(self):
        print("moving down")
        self.head_y += 1
        self.tail_follow()

    def tail_follow(self):
        # head has already moved, need to move the tail ?
        x_diff = self.tail_x - self.head_x
        y_diff = self.tail_y - self.head_y

        # if either of these are more than 2 different then we have to move
        diffs = [abs(x_diff), abs(y_diff)]
        diff_too_big = [True if x > 1 else False for x in diffs]

        if any(diff_too_big):
            # we need to move..
            if 0 != y_diff:
                # moving either up or down
                if y_diff > 0:
                    self.tail_y -= 1
                else:
                    self.tail_y += 1

            if 0 != x_diff:
                # moving either left or right
                if x_diff > 0:
                    self.tail_x -= 1
                else:
                    self.tail_x += 1

            # and we need to update the new position
            self.tail_visited.add((self.tail_x, self.tail_y))

        print(
            f"After move logic head={self.head_x},{self.head_y} tail={self.tail_x},{self.tail_y} tail_position count is now {self.tail_positions()}"
        )
        self.print_locale()

        # Sanity check - we should not need to move now..
        x_diff = self.tail_x - self.head_x
        y_diff = self.tail_y - self.head_y

        # if either of these are more than 2 different then we have to move
        diffs = [abs(x_diff), abs(y_diff)]
        diff_too_big = [True if x > 1 else False for x in diffs]
        if any(diff_too_big):
            raise Exception("What the hell?")

    def print_the_grid(self, min_x, min_y, max_x, max_y):
        for y in range(min_y, max_y, 1):
            s = ""
            for x in range(min_x, max_x, 1):
                this_spot = "."
                if (x, y) in self.tail_visited:
                    this_spot = "#"
                if 0 == x and 0 == y:
                    this_spot = "s"
                if self.tail_x == x and self.tail_y == y:
                    this_spot = "T"
                if self.head_x == x and self.head_y == y:
                    this_spot = "H"
                if (
                    self.tail_x == x
                    and self.tail_y == y
                    and self.head_x == x
                    and self.head_y == y
                ):
                    this_spot = "X"

                s += this_spot
            print(s)

    def print_locale(self, grid_size=8):
        # print out the small grid around the head and tail for debug purposes..
        min_x = min(self.head_x, self.tail_x) - grid_size
        min_y = min(self.head_y, self.tail_y) - grid_size
        max_x = max(self.head_x, self.tail_x) + grid_size + 1
        max_y = max(self.head_y, self.tail_y) + grid_size + 1

        self.print_the_grid(min_x, min_y, max_x, max_y)

    def print_all(self):
        # print the whole thing
        print(self.tail_visited)
        all_x = [a[0] for a in self.tail_visited]
        all_y = [a[1] for a in self.tail_visited]
        min_x = min(all_x) - 1
        max_x = max(all_x) + 1
        min_y = min(all_y) - 1
        max_y = max(all_y) + 1

        self.print_the_grid(min_x, min_y, max_x, max_y)

    def tail_positions(self):
        # how many unique places has the tail been ?
        return len(self.tail_visited)


def generate_rope_from_file(filename: str):

    the_rope = Rope()

    with open(filename, "r") as f:
        for this_line in f:
            this_line = this_line.strip()
            if "" != this_line:
                # lines are Direction<space>count
                parts = this_line.split(" ")
                direction = parts[0]
                move_count = int(parts[1])
                assert move_count > 0

                print(f"ORDER TO MOVE -> {direction} for {move_count}")

                # apply one move..
                for this_move in range(move_count):
                    if "R" == direction:
                        the_rope.move_right()
                    elif "L" == direction:
                        the_rope.move_left()
                    elif "U" == direction:
                        the_rope.move_up()
                    elif "D" == direction:
                        the_rope.move_down()
                    else:
                        raise Exception(
                            f"What the hell kind of direction is {direction} ??"
                        )

    return the_rope


def part1(filename: str):
    rope = generate_rope_from_file(filename)
    rope.print_all()
    result = rope.tail_positions()
    print(f"The number of tail positions for {filename} is {result}")
    return result


if __name__ == "__main__":
    sample_filename = "sample.txt"
    puzzle_filename = "input.txt"
    sample_expected_result = 13

    sample_actual = part1(sample_filename)
    assert sample_actual == sample_expected_result

    puzzle_result = part1(puzzle_filename)
